spring:
  profiles:
    active: production
  jpa:
    show-sql: false
    format_sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:postgresql://localhost:5432/mqi
    username: mqi
    password: mqi
    driver-class-name: org.postgresql.Driver
  devtools:
    restart:
      enabled: true

mqi:
  properties:
    system:
      version: 1.0.0
      pageSize: 5


logging:
  level:
    org:
      springframework:
        web: INFO
    io:
      egia:
        mqi: DEBUG

server:
  port: 8080
